name: CI para rama webintegral

on:
  push:
    branches:
      - Version1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # O la versión que uses

      - name: Instalar dependencias
        working-directory: ./webapp-jmmh
        run: npm install

      - name: Construir proyecto
        working-directory: ./webapp-jmmh
        run: npm run build

      - name: Confirmar éxito
        run: echo "Build y workflow completados en la rama webintegral"
